## =============================================================================
## Simulation 1: Nominal Network Estimation (3 Misconceptions)
## =============================================================================
##
## Description:
##   Runs the nominal network psychometric analysis on one simulated dataset
##   from Simulation 1. Estimates a LASSO-regularized multinomial logistic
##   regression network using glmnet, classifies all item-option pairs into
##   relationship groups, and computes average edge weights per group.
##
##   Designed to be submitted as an HPC array job, one job per replication.
##
## Usage (HPC array job):
##   Rscript network3_estimate_Argon.R <replication_number>
##   where <replication_number> is an integer from 1 to 1000.
##
## Input:
##   Data/ResponseMatrix3_C1_{c}.RData  (generated by SICM3_generate_Argon.R)
##
## Output:
##   NetworkResults/rep{c}.RData
##   Contains: qgraphMatrix (120x120 symmetric coefficient matrix),
##             qgraph_clean (long-format edge data with group labels),
##             qgraph_avg (per-group mean, SD, and n of nonzero edges)
##
## Item-option relationship groups:
##   "both correct"              - both options are correct answers (option 1)
##   "one correct"               - one option correct, one incorrect
##   "same misconception"        - both options reflect the same misconception
##   "correlated misconceptions" - options reflect misconceptions 1 & 2 (r=0.8)
##   "uncorrelated misconceptions" - options reflect unrelated misconceptions
##
## Method:
##   - Multinomial family glmnet with LASSO (alpha = 1), no intercept
##   - Lambda selected by 20-fold CV minimizing EBIC (gamma = 0.25)
##   - Symmetric matrix formed by averaging off-diagonal pairs
##
## Dependencies: glmnet, dplyr
## =============================================================================

args <- commandArgs(trailingOnly = TRUE)
c <- as.numeric(args[1])

library(glmnet)
library(dplyr)

# -----------------------------------------------------------------------------
# Load simulated dataset
# -----------------------------------------------------------------------------

load(paste0("Data/ResponseMatrix3_C1_{", c, "}.RData"))

data  <- as.data.frame(itemResponse)
names(data) <- seq_len(ncol(data))
nvar    <- ncol(data)
options <- 4  # number of response options per item

# -----------------------------------------------------------------------------
# Build predictor matrices and node name index
# -----------------------------------------------------------------------------

bigMatrixNames <- NULL
for (var in 1:nvar) {
  data[, var] <- as.factor(data[, var])
  levels(data[, var]) <- 1:options
  bigMatrixNames <- c(bigMatrixNames, paste0("V", var, ".O", 1:options))
}

# Initialize symmetric coefficient matrix (nodes = item-option combinations)
qgraphMatrix <- matrix(0,
                        nrow = length(bigMatrixNames),
                        ncol = length(bigMatrixNames))
rownames(qgraphMatrix) <- colnames(qgraphMatrix) <- bigMatrixNames

# -----------------------------------------------------------------------------
# Fit multinomial LASSO for each item (predicting that item from all others)
# -----------------------------------------------------------------------------

modelData     <- vector(mode = "list", length = nvar)
qgraphMatrixRow <- 0

for (var in 1:nvar) {
  predList <- (1:nvar)[-var]  # all items except current

  # Build design matrix of dummy-coded predictors
  tempMatrix <- model.matrix(formula(~0 + data[, predList[1]]), data = data)
  colnames(tempMatrix) <- paste0("V", predList[1], ".O", 1:options)
  for (pred in 2:length(predList)) {
    tempMatrix2 <- model.matrix(formula(~0 + data[, predList[pred]]), data = data)
    colnames(tempMatrix2) <- paste0("V", predList[pred], ".O", 1:options)
    tempMatrix <- cbind(tempMatrix, tempMatrix2)
  }

  modelData[[var]]$y <- data[, var]
  modelData[[var]]$x <- tempMatrix

  # Fit LASSO path and select lambda via 20-fold CV (minimizes EBIC)
  modelData[[var]]$cvFit <- cv.glmnet(
    x                  = modelData[[var]]$x,
    y                  = modelData[[var]]$y,
    family             = "multinomial",
    type.multinomial   = "grouped"
  )
  modelData[[var]]$optimal <- glmnet(
    x         = modelData[[var]]$x,
    y         = modelData[[var]]$y,
    family    = "multinomial",
    lambda    = modelData[[var]]$cvFit$lambda.min,
    intercept = FALSE
  )
  modelData[[var]]$coef <- coef(modelData[[var]]$optimal)

  # Fill coefficient matrix rows for each option of this item
  for (pred in 1:length(levels(modelData[[var]]$y))) {
    qgraphMatrixRow <- qgraphMatrixRow + 1
    values    <- modelData[[var]]$coef[pred][[1]]
    locations <- rownames(modelData[[var]]$coef[pred][[1]])
    qgraphMatrix[qgraphMatrixRow, locations[which(values != 0)]] <- values[which(values != 0)]
  }
}

# Symmetrize by averaging upper and lower triangles
qgraphMatrix <- (qgraphMatrix + t(qgraphMatrix)) / 2

# -----------------------------------------------------------------------------
# Classify item-option pairs into relationship groups
# -----------------------------------------------------------------------------

# Convert to long format (upper triangle only)
qgraph_long <- data.frame(
  row_index = rep(seq_len(nrow(qgraphMatrix)), times = ncol(qgraphMatrix)),
  col_index = rep(seq_len(ncol(qgraphMatrix)), each  = nrow(qgraphMatrix)),
  rowname   = rep(rownames(qgraphMatrix), times = ncol(qgraphMatrix)),
  colname   = rep(colnames(qgraphMatrix), each  = nrow(qgraphMatrix)),
  value     = as.vector(qgraphMatrix)
)
qgraph_upper <- qgraph_long[qgraph_long$row_index < qgraph_long$col_index,
                              c("rowname", "colname", "value")]

# Extract option number from node name (last character)
qgraph_upper$op1 <- as.numeric(substr(qgraph_upper$rowname,
                                       nchar(qgraph_upper$rowname),
                                       nchar(qgraph_upper$rowname)))
qgraph_upper$op2 <- as.numeric(substr(qgraph_upper$colname,
                                       nchar(qgraph_upper$colname),
                                       nchar(qgraph_upper$colname)))

# Remove zero edges
qgraph_clean <- qgraph_upper[qgraph_upper$value != 0, ]

# Assign relationship group labels
qgraph_clean$group <- NA

qgraph_clean$group[qgraph_clean$op1 == 1 & qgraph_clean$op2 == 1] <- "both correct"

qgraph_clean$group[qgraph_clean$op1 == 1 & qgraph_clean$op2 > 1]  <- "one correct"
qgraph_clean$group[qgraph_clean$op1 > 1  & qgraph_clean$op2 == 1] <- "one correct"

qgraph_clean$group[qgraph_clean$op1 != 1 &
                     qgraph_clean$op2 == qgraph_clean$op1]           <- "same misconception"

# Correlated: misconceptions 1 & 2 (options 2 & 3)
qgraph_clean$group[qgraph_clean$op1 == 2 & qgraph_clean$op2 == 3]  <- "correlated misconceptions"
qgraph_clean$group[qgraph_clean$op1 == 3 & qgraph_clean$op2 == 2]  <- "correlated misconceptions"

# Uncorrelated: misconceptions involving option 4
qgraph_clean$group[qgraph_clean$op1 == 2 & qgraph_clean$op2 == 4]  <- "uncorrelated misconceptions"
qgraph_clean$group[qgraph_clean$op1 == 4 & qgraph_clean$op2 == 2]  <- "uncorrelated misconceptions"
qgraph_clean$group[qgraph_clean$op1 == 3 & qgraph_clean$op2 == 4]  <- "uncorrelated misconceptions"
qgraph_clean$group[qgraph_clean$op1 == 4 & qgraph_clean$op2 == 3]  <- "uncorrelated misconceptions"

# -----------------------------------------------------------------------------
# Compute per-group summary statistics (mean, SD, n of nonzero edges)
# -----------------------------------------------------------------------------

qgraph_avg <- merge(
  x         = aggregate(value ~ group, data = qgraph_clean, FUN = mean),
  y         = aggregate(value ~ group, data = qgraph_clean, FUN = sd),
  by        = "group",
  suffixes  = c("_mean", "_sd")
)
qgraph_avg$n <- as.numeric(table(qgraph_clean$group)[qgraph_avg$group])

# -----------------------------------------------------------------------------
# Save results
# -----------------------------------------------------------------------------

if (!dir.exists("NetworkResults")) dir.create("NetworkResults")

save.image(file = paste0("NetworkResults/rep", c, ".RData"))

cat("Replication", c, "complete. Groups found:", paste(qgraph_avg$group, collapse = ", "), "\n")
